version: "3.8"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      robonauth.api-key: BSS
      spring.data.mongodb.host: mongo
      spring.rabbitmq.host: rabbitmq
    ports:
    - "127.0.0.1:8080:8080"
  rabbitmq:
    image: rabbitmq:3.9.13-management-alpine
    ports:
    - "127.0.0.1:5672:5672"
    - "127.0.0.1:8081:15672"
  mongo:
    image: mongo:4.4.6-bionic
    ports:
    - "127.0.0.1:27017:27017"
