version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.9.13-management-alpine
    ports:
    - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 40s
  mongo:
    image: mongo:4.4.6-bionic
    ports:
    - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
