services:
  app:
    build: ./
    environment:
      robonauth.api-key: BSS
      spring.mongodb.host: mongo
      spring.rabbitmq.host: rabbitmq
    profiles:
      - app
    ports:
    - "127.0.0.1:8080:8080"
    healthcheck:
      test:  "wget --tries=1 --no-verbose -qO- http://localhost:8080/actuator/health/readiness | grep -q UP"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
  rabbitmq:
    image: "rabbitmq:4.3.6-management-alpine@sha256:537be5b43147e363edd5f2211ba9bd5769ba7ed64b329b0b6d1cbfa1c0e61df8"
    ports:
    - "127.0.0.1:5672:5672"
    - "127.0.0.1:15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 40s
  mongo:
    image: "mongo:8.3.11@sha256:2609aaf7a1abbff404101af896e05f243d22be742471ed857b50b9ce0270fdbd"
    ports:
    - "127.0.0.1:27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
