services:
  app:
    build: ./
    environment:
      robonauth.api-key: BSS
      spring.mongodb.host: mongo
      spring.rabbitmq.host: rabbitmq
    profiles:
      - app
    ports:
    - "127.0.0.1:8080:8080"
    healthcheck:
      test:  "wget --tries=1 --no-verbose -qO- http://localhost:8080/actuator/health/readiness | grep -q UP"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
  rabbitmq:
    image: "rabbitmq:4.3.4-management-alpine@sha256:3715356a45c617db988228af10b959a226c832f90298bf7155033c30222ff1df"
    ports:
    - "127.0.0.1:5672:5672"
    - "127.0.0.1:15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 40s
  mongo:
    image: "mongo:8.3.7@sha256:a7f5aa200005611166adcec0192c2f11d0acc3bfd9d5eb68e1a998a990412e41"
    ports:
    - "127.0.0.1:27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
