services:
  app:
    build: ./
    environment:
      robonauth.api-key: BSS
      spring.mongodb.host: mongo
      spring.rabbitmq.host: rabbitmq
    profiles:
      - app
    ports:
    - "127.0.0.1:8080:8080"
    healthcheck:
      test:  "wget --tries=1 --no-verbose -qO- http://localhost:8080/actuator/health/readiness | grep -q UP"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
  rabbitmq:
    image: "rabbitmq:4.3.4-management-alpine@sha256:44bf7eb50fe1765885659e49ccfdc775f8e531964d979321aee380a071f49f94"
    ports:
    - "127.0.0.1:5672:5672"
    - "127.0.0.1:15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 40s
  mongo:
    image: "mongo:8.3.8@sha256:4e81cd5857d7a087db95c6c1c2d8fd9feddfef58d1bf5b754356d20f583744d1"
    ports:
    - "127.0.0.1:27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
