version: "3.8"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      robonauth.api-key: BSS
      spring.data.mongodb.host: mongo
      spring.rabbitmq.host: rabbitmq
    ports:
    - "8080:8080" # change it to "127.0.0.1:8080:8080" for localhost only
  rabbitmq:
    image: rabbitmq:3.9.13-management-alpine
    ports:
    - "5672:5672" # change it to "127.0.0.1:5672:5672" for localhost only
    - "8081:15672" # change it to "127.0.0.1:8081:15672" for localhost only
  mongo:
    image: mongo:4.4.6-bionic
    ports:
    - "27017:27017" # change it to "127.0.0.1:27017:27017" for localhost only
