version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: ./gradlew
      - run: ./gradlew check --parallel
      - store_test_results:
          path: ./web/build/test-results
  integration-test:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run: docker-compose -f ./docker-compose.test.yaml up --build --abort-on-container-exit
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - integration-test