version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-buster
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle clean build --parallel
  integration-test:
    docker:
      - image: circleci/openjdk:11-jdk-buster
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: docker-compose up --build --abort-on-container-exit ./docker-compose.test.yaml
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - integration-test