version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:14-jdk-buster
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle clean build --parallel
  integration-test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: docker-compose up --build --abort-on-container-exit
