version: 2.1
orbs:
  codecov: codecov/codecov@5.4.3
  gradle: circleci/gradle@4.0.0
  node: circleci/node@7.2.1
executors:
  jdk:
    docker:
      - image: cimg/openjdk:21.0.8@sha256:4a801120973f503e4e2c2c83b8ee25f1fec7935c1fa3c455fb61f5773b5af7ae
  node:
    docker:
      - image: cimg/node:22.20.0@sha256:ff10c636544b4bd7aa2efb057ba1d1140e2473766f07136321303afe6d15e9a4
  node-machine:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true
defaults:
  gradle: &gradle
    deps_checksum_file: build.gradle.kts
    cache_key: v2
    executor: jdk
jobs:
  gradle:
    parameters:
      command:
        type: string
      after:
        type: steps
        default: []
    executor: jdk
    steps:
      - checkout
      - gradle/with_cache:
          deps_checksum_file: build.gradle.kts
          cache_key: v2
          steps:
            - run: ./gradlew << parameters.command >>
      - steps: << parameters.after >>
  integration_test:
    executor: node-machine
    steps:
      - checkout
      - node/install-pnpm
      - node/install-packages:
          pkg-manager: pnpm
      - run:
          command: pnpm run -r test:ci
          environment:
            DEBUG: testcontainers
      - store_test_results:
          path: ~/project/integration/reports
  lint_integration:
    executor: node
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: pnpm
      - run:
          command: pnpm run -r lint
workflows:
  Build app:
    jobs:
      - gradle/run:
          name: Lint
          command: spotlessCheck
          <<: *gradle
      - gradle/run:
          name: Build boot jar
          command: bootJar
          <<: *gradle
      - gradle:
          name: Unit test
          command: test --continue
          after:
            - run:
                name: Save test results
                command: |
                  mkdir -p test-results/junit/
                  find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} test-results/junit/ \;
            - gradle/collect_test_results:
                reports_path: server/build/reports
                test_results_path: test-results
      - gradle:
          name: Coverage
          command: jacocoTestCoverageVerification
          after:
            - codecov/upload:
                flags: unit
      - lint_integration:
          name: Lint Integration test
      - integration_test:
          name: Integration test
